### ISSUE TITLE
Описать модель `User`

### ISSUE THREAD

**Issue by NiKuma0** [Studio-Yandex-Practicum/RandomCoffeeBot#22]
# How To Do?

Не забыть использовать синтаксис sqlalchemy 2.0
```
User: 
  username: str
  first_name: str
  last_name: str
  status - Тут будет объект Enums пока только с полями `IN_MEETING`, `WAITING_MEETING` и `NOT_INVOLVED`
 
``` 
Также нужно описать простой скрипт создания таблиц, чтобы все проверить.

# Where?
`src/db/models.py`
